export const ADD_USER = 'ADD_USER'
export const ADD_USER_OK = 'ADD_USER_OK'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const BEGIN_USERS_DOWNLOAD = 'BEGIN_USERS_DOWNLOAD'
export const USERS_DOWNLOAD_OK = 'USERS_DOWNLOAD_OK'
export const USERS_DOWNLOAD_ERROR = 'USERS_DOWNLOAD_ERROR'

export const RETRIEVE_USER_DELETE = 'RETRIEVE_USER_DELETE'
export const USER_DELETED_OK = 'USER_DELETED_OK'
export const USER_DELETED_ERROR = 'USER_DELETED_ERROR'

export const RETRIEVE_USER_EDIT= 'RETRIEVE_USER_EDIT'
export const BEGIN_EDIT_USER = 'BEGIN_EDIT_USER'
export const USER_EDITED_OK = 'USER_EDITED_OK'
export const USER_EDITED_ERROR = 'USER_EDITED_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const USER_PAGE_ADD = "USER_PAGE_ADD"